on:
  push:
    branches: '**'
    tags-ignore: '**'
  pull_request:
  release:
    types: [published]

name: ci

env:
  RELEASE: ${{ github.event_name == 'release' && '--release' || '' }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - run: sudo apt-get update && sudo apt-get install cargo libgtk-3-dev libudev-dev patchelf
    - uses: actions/checkout@v2
    - run: cd linux && ./build.py $RELEASE
    - id: version
      run: echo ::set-output version=$(./.github/workflows/version.py)
    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: keyboard-configurator-linux-x86_64-${{ github.sha }}
        path: linux/keyboard-configurator-x86_64.AppImage

  upload-to-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    #needs: [linux-x86_64, windows-mingw32, macos]
    needs: [linux-x86_64]
    steps:
    - uses: actions/download-artifact@v2
    - run: echo VERSION=${{ needs.linux-x86_64.outputs.version }}
    - run: echo VERSION=${{ needs.linux-x86_64.outputs.version }} > $GITHUB_ENV
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: keyboard-configurator-linux-x86_64-${{ github.sha }}/keyboard-configurator-x86_64.AppImage
        asset_name: keyboard-configurator-${{ env.VERSION }}-x86_64.AppImage
        asset_content_type: application/vnd.appimage
